### ISSUE TITLE
w2v question

### ISSUE THREAD

**Issue by MerceaOtniel** [hbdat/neurIPS20_CompositionZSL#1]
Hello! Thank you for making public the code for this project!

I would have a question related to `neurIPS20_CompositionZSL/w2v/CUB_class.pkl`. Does this file contain the word2vec embeddings or GloVe embeddings for the classes in CUB? I am a bit confused as it seems that the attributes are extracted with word2vec while class names with GloVe, but in the paper it is said the attributes are extracted with GloVe. 

Moreover, is it safe to assume that the order of these embeddings in the file is according to` CUB_200_2011/classes.txt`?

Looking into the `neurIPS20_CompositionZSL/extract_feature/class_semantic/extract_class_w2v_CUB.py` seems to imply that the order is the same as `CUB_200_2011/classes.txt` but I wanted to just make sure, as I get some errors when running `extract_class_w2v_CUB.py` related to some missing links and I would rather use the `.pkl` if it contains the embeddings.

Thank you

**Comment by hbdat** [comment]
Hi @MerceaOtniel,

Thanks for reaching out.
As you have mentioned, I use the `./extract_feature/class_semantic/extract_class_w2v_CUB.py` and `./extract_feature/extract_attribute_w2v_CUB.py` to construct the `./w2v/CUB_class.pkl` and `./w2v/CUB_attribute.pkl` files, respectively. These are based on word2vec model and not GloVe (Sorry for the confusion).

Thus, the order of `CUB_class.pkl` would follow `CUB_200_2011/classes.txt`.

Please let me know if you have any further questions.
Hope this helps.

Best,
Dat
